name: Deploy Cloud Function

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Decode service account
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > "${HOME}/gcp-key.json"

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ secrets.GCP_SA_KEY }}"

    - name: Deploy to Cloud Functions
      uses: google-github-actions/deploy-cloud-functions@v1
      with:
        name: palmChatbot
        runtime: python310
        entry_point: chatbot
        region: us-central1
        source_dir: .
        trigger_http: true
        allow_unauthenticated: true
