name: Test and Deploy Cloud Function

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # remove if not using pytest

      - name: Run tests (if any)
        run: |
          pytest || echo "No tests found"

      - name: Decode service account key
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > $HOME/gcp-key.json

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy palmChatbot \
            --region=us-central1 \
            --runtime=python310 \
            --trigger-http \
            --entry-point=chatbot \
            --memory=512MB \
            --allow-unauthenticated \
            --source=.